version: '3'

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - "mongodata:/data"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    environment:
      ES_MAX_MEM: 1g
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    ports:
     - "9200:9200"
     - "9300:9300"

  graylog:
    image: graylog/graylog:4.0
    environment:
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      GRAYLOG_MONGODB_URI: mongodb://mongodb.service/graylog
      GRAYLOG_MONGODB_MAX_CONNECTIONS: 100
      GRAYLOG_MONGODB_THREADS_ALLOWED_TO_BLOCK_MULTIPLIER: 5
      GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: graylog
    restart: always
    volumes:
      - "graylogdata:/opt/graylog/data"
    links:
      - "elasticsearch:elasticsearch"
      - "mongodb:mongodb.service"
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"
    depends_on:
      - elasticsearch
      - mongodb
  app:
    hostname: worker1
    build: .

  app2:
    hostname: worker2
    build: .

volumes:
  esdata:
    driver: local
  graylogdata:
    driver: local
  mongodata:
    driver: local
